name = "Slim"
license = "MIT"
licenselink = "https://github.com/sedenardi/slim/blob/master/LICENSE"
description = "Minimal blog theme for Hugo."
min_version = 0.17

[author]
  name = "Sanders DeNardi"
  homepage = "www.sandersdenardi.com"
